services:
  import:
    image: markis/dynasty-import-job
    build:
      context: .
      dockerfile: Containerfile
    env_file: .env
    volumes:
      - /opt/dynastyprocess-data/:/Users/markis/src/dynastyprocess-data/
    entrypoint: ["python", "-m"]
    command: ["dynasty.import"]

  app:
    image: markis/dynasty
    build:
      context: .
      dockerfile: Containerfile
    entrypoint: ["streamlit", "run"]
    command: ["/src/home.py"]
    ports:
      - 8501:8501
