name: check

on:
  pull_request:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"
      - name: Install Hatch
        run: pipx install hatch
      - name: Check Format
        run: hatch fmt

  types:
    name: types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"
      - name: Install Hatch
        run: pipx install hatch
      - name: Check Types
        run: hatch run types:check

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"
      - name: Install Hatch
        run: pipx install hatch
      - name: Run Tests
        run: hatch tests
